name: Mirror OpenCanary & Push to Docker Hub

on:
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

jobs:
  mirror_to_docker_hub:
    name: Mirror Repo
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Clone Open Canary
        run: |
          git clone https://github.com/thinkst/opencanary.git .
          cp Dockerfile.latest Dockerfile
          ls -lah
          pwd

      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: mcnamee/opencanary

      -
        name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: mcnamee/opencanary:latest
